Improve code
hpi-epic/pricing_competition_simulation pull request #18
Opened 2018-05-18 09:03 UTC by tomschw

Reformat code for better readability

2018-05-18 12:46 UTC, Bouncner requested changes
First batch of short comments. In general: please add more helping comments.

Besides that: looks much better now!

2018-05-18 12:46 UTC, Bouncner commented on monte_carlo.ipynb
> +    "watched_firm = 0\n",
Could you add short comments here?

2018-05-18 12:46 UTC, Bouncner commented on monte_carlo.ipynb
> +    "num_market_situations = 10   # value used for paper: 40\n",
What does this variable do?

2018-05-18 12:46 UTC, Bouncner commented on intensity.ipynb
> +    "prices_firm = np.array([\n",
Why no numpy uniform here?

2018-05-18 12:46 UTC, Bouncner commented on intensity.ipynb
> +    "    for i in range(1,len(prices_firm_adjust)-1):        \n",
Short comment, why having this 'strange' indexing in the for loop.

2018-05-21 13:22 UTC, tomschw commented
@Bouncner Updated each file which should answer all your questions.
I also changed the price_if_smaller_else function (#16), is it better?

2018-08-24 09:13 UTC, merged